import type { SurveyQuestion } from "./types";

/**
 * Single source of truth for every survey question.
 * IDs are meaning-based (Cowork 설계안 방식). Numeric IDs are never used here.
 *
 * Wording/options follow the Cowork survey flow. Metadata flags drive
 * validation, conditional branching, dashboard/PDF visibility, risk flags,
 * and (later) health-score candidates.
 */
export const QUESTIONS: SurveyQuestion[] = [
  // ── basic ───────────────────────────────────────────────
  {
    id: "basic_name",
    section: "basic",
    order: 1,
    label: "성함",
    type: "short_text",
    required: true,
    sensitivity: "personal",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "basic_rrn",
    section: "basic",
    order: 2,
    label: "주민등록번호",
    helperText:
      "원활한 상담과 본인 확인을 위해 뒷자리까지 작성해 주세요. ('-' 없이 숫자만)",
    type: "short_text",
    required: true,
    sensitivity: "unique_id",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "basic_phone",
    section: "basic",
    order: 3,
    label: "연락처",
    type: "short_text",
    required: true,
    sensitivity: "personal",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "basic_address",
    section: "basic",
    order: 4,
    label: "주소",
    type: "short_text",
    required: true,
    sensitivity: "personal",
    dashboard: true,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "basic_sex",
    section: "basic",
    order: 5,
    label: "성별",
    type: "single_choice",
    options: ["여성", "남성"],
    required: true,
    sensitivity: "personal",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "basic_birth_count",
    section: "basic",
    order: 6,
    label: "출산 경험",
    type: "single_choice",
    options: ["없음", "1회", "2회", "3회 이상"],
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "basic_referral",
    section: "basic",
    order: 7,
    label: "내원 경로",
    helperText: "어떻게 저희를 알게 되셨나요?",
    type: "single_choice",
    options: ["지인 소개", "인터넷 검색", "SNS", "기타"],
    required: false,
    sensitivity: "general",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "basic_referrer",
    section: "basic",
    order: 8,
    label: "소개해주신 분",
    helperText: "지인 소개로 오신 경우에만 적어 주세요.",
    type: "short_text",
    required: false,
    sensitivity: "general",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
    conditional: { questionId: "basic_referral", operator: "equals", value: "지인 소개" },
  },

  // ── consent ─────────────────────────────────────────────
  {
    id: "consent_agree",
    section: "consent",
    order: 1,
    label: "개인정보·건강정보 및 민감 건강정보 수집·활용에 동의합니다",
    helperText:
      "본 의원은 맞춤 진료·예약 안내 목적에 한해 성명, 주민등록번호, 연락처, 주소와 건강·민감 건강정보를 수집·활용하며, 제3자에게 제공하지 않습니다.",
    type: "yes_no",
    required: true,
    sensitivity: "personal",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
  },

  // ── goal ────────────────────────────────────────────────
  {
    id: "goal_reason",
    section: "goal",
    order: 1,
    label: "지금 이 클리닉을 찾아오신 가장 큰 이유는 무엇인가요?",
    type: "long_text",
    required: true,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "goal_3month",
    section: "goal",
    order: 2,
    label: "3개월 후, 어떤 몸 상태가 되어 있기를 바라시나요?",
    helperText: "체중 숫자보다, 어떻게 느끼고 싶은지를 중심으로 적어 주세요.",
    type: "long_text",
    required: true,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "goal_concern_areas",
    section: "goal",
    order: 3,
    label: "현재 가장 불편하거나 신경 쓰이는 부분",
    helperText: "해당하는 것을 모두 선택해 주세요.",
    type: "multiple_choice",
    options: [
      "체중 및 체형",
      "만성 피로, 무기력함",
      "수면의 질",
      "소화·장 건강",
      "부종",
      "호르몬·생리 주기",
      "피부 컨디션",
      "식욕 조절",
      "혈당·혈압·콜레스테롤",
    ],
    allowOther: true,
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "goal_quality_of_life",
    section: "goal",
    order: 4,
    label: "체중 외에, 삶의 질에서 개선되기를 원하는 것",
    helperText: "예: 아침에 개운하게 일어나고 싶다 · 식후 졸음이 없어졌으면 한다",
    type: "long_text",
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },

  // ── body_metrics ────────────────────────────────────────
  {
    id: "body_weight_current",
    section: "body_metrics",
    order: 1,
    label: "현재 체중 (kg)",
    type: "number",
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: true,
    scoreDomain: "체중 변화",
    riskFlag: false,
  },
  {
    id: "body_height",
    section: "body_metrics",
    order: 2,
    label: "키 (cm)",
    type: "number",
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "body_weight_target",
    section: "body_metrics",
    order: 3,
    label: "목표 체중 (kg)",
    type: "number",
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: true,
    scoreDomain: "체중 변화",
    riskFlag: true,
  },
  {
    id: "body_weight_min",
    section: "body_metrics",
    order: 4,
    label: "평생 최저 체중 (kg)",
    type: "number",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "body_weight_pre_birth",
    section: "body_metrics",
    order: 5,
    label: "출산 전 체중 (kg)",
    type: "number",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
    conditional: { questionId: "basic_birth_count", operator: "not_equals", value: "없음" },
  },
  {
    id: "body_weight_post_birth",
    section: "body_metrics",
    order: 6,
    label: "출산 후 체중 (kg)",
    type: "number",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
    conditional: { questionId: "basic_birth_count", operator: "not_equals", value: "없음" },
  },
  {
    id: "body_focus_area",
    section: "body_metrics",
    order: 7,
    label: "가장 신경 쓰이는 부위",
    helperText: "예: 복부, 허벅지 탄력, 팔뚝 등",
    type: "short_text",
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },

  // ── diet_history ────────────────────────────────────────
  {
    id: "diet_tried",
    section: "diet_history",
    order: 1,
    label: "지금까지 다이어트를 시도해 보신 적이 있으신가요?",
    type: "single_choice",
    options: ["없음", "있음"],
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "diet_methods",
    section: "diet_history",
    order: 2,
    label: "시도해 본 방법",
    helperText: "해당하는 것을 모두 선택해 주세요.",
    type: "multiple_choice",
    options: [
      "한방 치료(한약·약침 등)",
      "양방 치료(식욕억제제·지방분해 주사 등)",
      "식이 조절(간헐적 단식·저탄고지 등)",
      "다이어트 보조식품",
      "운동(PT·필라테스·수영 등)",
      "체형 시술(지방흡입 등)",
    ],
    allowOther: true,
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
    conditional: { questionId: "diet_tried", operator: "equals", value: "있음" },
  },
  {
    id: "diet_history_note",
    section: "diet_history",
    order: 3,
    label: "과거 다이어트에서 잘 되었던 점과 어려웠던 점",
    helperText: "예: 초반엔 잘 되다가 요요가 왔다 · 식욕 조절이 늘 가장 힘들었다",
    type: "long_text",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
    conditional: { questionId: "diet_tried", operator: "equals", value: "있음" },
  },

  // ── sleep ───────────────────────────────────────────────
  {
    id: "sleep_bedtime",
    section: "sleep",
    order: 1,
    label: "평균 취침 시간",
    type: "time",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "sleep_waketime",
    section: "sleep",
    order: 2,
    label: "평균 기상 시간",
    type: "time",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "sleep_latency_min",
    section: "sleep",
    order: 3,
    label: "잠들기까지 걸리는 시간 (분)",
    type: "number",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: true,
    scoreDomain: "수면",
    riskFlag: false,
  },
  {
    id: "sleep_quality",
    section: "sleep",
    order: 4,
    label: "수면의 질",
    helperText: "해당하는 것을 모두 선택해 주세요.",
    type: "multiple_choice",
    options: [
      "수면으로 특별한 불편함이 없다",
      "자다가 여러 번 깬다",
      "중간에 깨면 다시 잠들기 어렵다",
      "피곤해도 아침 일정 시간에 저절로 깬다",
      "걱정거리가 있으면 2~3시간 이상 뒤척인다",
      "거의 날을 새우다시피 한다",
    ],
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: true,
    scoreDomain: "수면",
    riskFlag: true,
  },
  {
    id: "sleep_blackout_curtain",
    section: "sleep",
    order: 5,
    label: "암막 커튼",
    type: "single_choice",
    options: ["있음", "없음"],
    required: false,
    sensitivity: "general",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "sleep_bedroom_tv",
    section: "sleep",
    order: 6,
    label: "침실 TV",
    type: "single_choice",
    options: ["있음", "없음"],
    required: false,
    sensitivity: "general",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "sleep_light",
    section: "sleep",
    order: 7,
    label: "취침 시 불",
    type: "single_choice",
    options: ["켜고 잠", "끄고 잠"],
    required: false,
    sensitivity: "general",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "sleep_temp",
    section: "sleep",
    order: 8,
    label: "침실 온도",
    type: "single_choice",
    options: ["서늘하게", "따뜻하게", "잘 모름"],
    required: false,
    sensitivity: "general",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "sleep_humidity",
    section: "sleep",
    order: 9,
    label: "침실 습도",
    type: "single_choice",
    options: ["건조한 편", "적당함", "습한 편"],
    required: false,
    sensitivity: "general",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "sleep_phone_position",
    section: "sleep",
    order: 10,
    label: "스마트폰을 주로 어디에 두고 주무시나요?",
    type: "single_choice",
    options: ["베개 바로 옆", "침대 위 손 닿는 곳", "침대에서 멀리", "침실 밖"],
    required: false,
    sensitivity: "general",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "sleep_aid_use",
    section: "sleep",
    order: 11,
    label: "수면 보조제나 안정제를 복용하고 계신가요?",
    type: "single_choice",
    options: ["없음", "가끔 복용", "정기적으로 복용 중"],
    required: false,
    sensitivity: "sensitive_health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: true,
  },

  // ── meal ────────────────────────────────────────────────
  {
    id: "meal_time_breakfast",
    section: "meal",
    order: 1,
    label: "아침 식사 시간",
    type: "time",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "meal_time_lunch",
    section: "meal",
    order: 2,
    label: "점심 식사 시간",
    type: "time",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "meal_time_dinner",
    section: "meal",
    order: 3,
    label: "저녁 식사 시간",
    type: "time",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "meal_time_latenight",
    section: "meal",
    order: 4,
    label: "야식 시간 (있는 경우)",
    type: "time",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "meal_regularity",
    section: "meal",
    order: 5,
    label: "끼니별 규칙성",
    type: "scale_grid",
    gridRows: ["아침", "점심", "저녁"],
    gridCols: ["규칙적", "불규칙"],
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: true,
    scoreDomain: "식사 규칙성",
    riskFlag: false,
  },
  {
    id: "meal_habits",
    section: "meal",
    order: 6,
    label: "식사 습관",
    helperText: "해당하는 것을 모두 선택해 주세요.",
    type: "multiple_choice",
    options: [
      "바쁠 때 끼니를 자주 건너뛴다",
      "탄수화물 위주의 식사를 한다(밥·빵·면·과자 등)",
      "국물이나 찌개류를 즐겨 먹는다",
      "과식하는 경향이 있다",
      "폭식 후 죄책감을 느낀 경험이 있다",
      "끼니 사이에 간식을 자주 먹는다",
      "식사 중 물이나 음료를 많이 마신다",
      "특별히 문제가 없다고 생각한다",
    ],
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: true,
    scoreDomain: "식욕·식습관",
    riskFlag: true,
  },
  {
    id: "meal_hungriest_time",
    section: "meal",
    order: 7,
    label: "배가 가장 고픈 시간대",
    type: "single_choice",
    options: ["아침", "점심 이후 오후", "저녁", "취침 전~새벽"],
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "meal_skip_reaction",
    section: "meal",
    order: 8,
    label: "끼니를 놓쳤을 때 반응",
    type: "single_choice",
    options: [
      "반드시 무언가 먹어야 불안하다",
      "크게 개의치 않는다",
      "오히려 다음 끼니에 더 많이 먹게 된다",
    ],
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "meal_speed",
    section: "meal",
    order: 9,
    label: "식사 속도",
    type: "single_choice",
    options: ["매우 빠른 편(5~10분 이내)", "보통", "천천히 먹는 편"],
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "meal_appetite",
    section: "meal",
    order: 10,
    label: "식욕의 강도",
    type: "single_choice",
    options: [
      "먹어도 금방 다시 배고프다",
      "왕성한 편이다",
      "보통이다",
      "적은 편이다",
      "최근 들어 입맛이 많이 떨어졌다",
    ],
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: true,
    scoreDomain: "식욕·식습관",
    riskFlag: true,
  },

  // ── alcohol_caffeine ────────────────────────────────────
  {
    id: "alcohol_freq_week",
    section: "alcohol_caffeine",
    order: 1,
    label: "음주 빈도 (주 몇 회)",
    type: "short_text",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: true,
    scoreDomain: "복약/기호식품",
    riskFlag: false,
  },
  {
    id: "alcohol_type",
    section: "alcohol_caffeine",
    order: 2,
    label: "주요 주종",
    type: "single_choice",
    options: ["소주", "맥주", "와인", "위스키"],
    allowOther: true,
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "alcohol_amount",
    section: "alcohol_caffeine",
    order: 3,
    label: "1회 음주량",
    helperText: "예: 소주 1병",
    type: "short_text",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "alcohol_with_meal",
    section: "alcohol_caffeine",
    order: 4,
    label: "음주 시 식사",
    type: "single_choice",
    options: ["물만", "가벼운 안주", "고기류", "식욕이 늘어 많이 먹는다"],
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "caffeine_cups_day",
    section: "alcohol_caffeine",
    order: 5,
    label: "하루 커피 섭취량 (잔)",
    type: "number",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: true,
    scoreDomain: "복약/기호식품",
    riskFlag: false,
  },
  {
    id: "caffeine_time",
    section: "alcohol_caffeine",
    order: 6,
    label: "주로 마시는 시간",
    type: "short_text",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "caffeine_reaction",
    section: "alcohol_caffeine",
    order: 7,
    label: "카페인 반응",
    type: "single_choice",
    options: ["잘 잠", "오후엔 못 잠", "심장 두근거림", "속 쓰림", "커피를 못 마심"],
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },

  // ── hydration ───────────────────────────────────────────
  {
    id: "hydration_pattern",
    section: "hydration",
    order: 1,
    label: "평소 수분 섭취 방식",
    helperText: "해당하는 것을 모두 선택해 주세요.",
    type: "multiple_choice",
    options: [
      "식사 중 물이나 음료를 함께 마신다",
      "식전에 물을 마신다",
      "식후에 물을 마신다",
      "식사 시간에는 물을 마시지 않는다",
      "평소에 물을 잘 마시지 않는다",
    ],
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: true,
    scoreDomain: "수분",
    riskFlag: false,
  },
  {
    id: "urine_color",
    section: "hydration",
    order: 2,
    label: "소변 색깔",
    type: "single_choice",
    options: ["거의 투명", "연한 노란색", "진한 노란색", "주황색 또는 갈색", "거품이 섞여 있다"],
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: true,
    scoreDomain: "수분",
    riskFlag: true,
  },

  // ── body_signal ─────────────────────────────────────────
  {
    id: "signal_temp_energy",
    section: "body_signal",
    order: 1,
    label: "체온 감각과 에너지 상태",
    helperText: "해당하는 것을 모두 선택해 주세요.",
    type: "multiple_choice",
    options: [
      "추위를 많이 탄다",
      "더위를 많이 탄다",
      "손발이 자주 차다",
      "아랫배가 차갑게 느껴진다",
      "체력이 좋은 편이다",
      "쉽게 지치는 편이다",
      "최근 들어 컨디션이 많이 떨어졌다",
    ],
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: true,
    scoreDomain: "피로·에너지",
    riskFlag: true,
  },
  {
    id: "signal_sweat",
    section: "body_signal",
    order: 2,
    label: "땀이 나는 패턴",
    type: "single_choice",
    options: ["많이 나는 편", "보통", "거의 나지 않는다", "식사 중에 유독 많이 난다", "잘 때 많이 난다"],
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "signal_edema",
    section: "body_signal",
    order: 3,
    label: "부종",
    type: "single_choice",
    options: ["자주 붓는다", "가끔 붓는다", "거의 붓지 않는다"],
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: true,
    scoreDomain: "부종",
    riskFlag: false,
  },
  {
    id: "signal_edema_area",
    section: "body_signal",
    order: 4,
    label: "주로 붓는 부위",
    helperText: "자주·가끔 붓는 경우에만 답해 주세요.",
    type: "multiple_choice",
    options: ["얼굴", "손", "발", "전신"],
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: false,
    scoreCandidate: false,
    riskFlag: true,
    conditional: { questionId: "signal_edema", operator: "not_equals", value: "거의 붓지 않는다" },
  },
  {
    id: "signal_digestion",
    section: "body_signal",
    order: 5,
    label: "소화 상태",
    type: "single_choice",
    options: ["소화가 잘 되는 편이다", "소화가 잘 안 된다"],
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: false,
    scoreCandidate: true,
    scoreDomain: "소화",
    riskFlag: false,
  },
  {
    id: "signal_digestion_symptoms",
    section: "body_signal",
    order: 6,
    label: "해당 증상",
    helperText: "소화가 잘 안 되는 경우에만 답해 주세요.",
    type: "multiple_choice",
    options: ["속쓰림", "신물", "메스꺼움", "복통", "트림", "가스 참"],
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
    conditional: { questionId: "signal_digestion", operator: "equals", value: "소화가 잘 안 된다" },
  },
  {
    id: "signal_bowel_freq",
    section: "body_signal",
    order: 7,
    label: "배변 빈도",
    type: "single_choice",
    options: ["매일 1회", "2~3일에 1회", "하루 2~3회"],
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "signal_stool",
    section: "body_signal",
    order: 8,
    label: "변 상태",
    type: "single_choice",
    options: ["정상", "무른 편", "단단한 편"],
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },

  // ── female (성별 여성일 때만) ───────────────────────────
  {
    id: "female_menstrual",
    section: "female",
    order: 1,
    label: "생리 주기 관련 해당 항목",
    helperText: "해당하는 것을 모두 선택해 주세요.",
    type: "multiple_choice",
    options: [
      "생리 주기가 불규칙한 편이다",
      "생리통이 심한 편이다",
      "생리 전 증후군(PMS)이 있다",
      "특별한 문제가 없다",
    ],
    required: false,
    sensitivity: "sensitive_health",
    dashboard: true,
    pdf: true,
    scoreCandidate: true,
    scoreDomain: "생리주기",
    riskFlag: false,
  },

  // ── medical ─────────────────────────────────────────────
  {
    id: "medical_conditions",
    section: "medical",
    order: 1,
    label: "현재 또는 과거에 진단받은 질환",
    helperText: "해당하는 것을 모두 선택해 주세요.",
    type: "multiple_choice",
    options: [
      "없음",
      "고혈압·심혈관 질환",
      "당뇨·공복혈당장애",
      "고지혈증",
      "갑상선 질환",
      "위염·역류성 식도염",
      "자궁·난소 질환",
      "불면증",
      "우울증·불안증",
      "자가면역 질환(아토피·건선 등)",
      "신장 질환",
    ],
    allowOther: true,
    required: false,
    sensitivity: "sensitive_health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: true,
  },
  {
    id: "medical_surgery",
    section: "medical",
    order: 2,
    label: "수술 이력",
    helperText: "수술 이력이 있는 경우에만 적어 주세요.",
    type: "short_text",
    required: false,
    sensitivity: "sensitive_health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "medical_medications",
    section: "medical",
    order: 3,
    label: "현재 복용 중인 약이나 보조제",
    helperText: "해당하는 것을 모두 선택해 주세요.",
    type: "multiple_choice",
    options: [
      "없음",
      "건강보조식품(홍삼·비타민·유산균 등)",
      "피임약·피임 시술",
      "수면제·신경안정제·항우울제",
      "알레르기 치료약",
      "스테로이드제",
    ],
    allowOther: true,
    required: false,
    sensitivity: "sensitive_health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: true,
  },
  {
    id: "medical_food_allergy",
    section: "medical",
    order: 4,
    label: "음식 알레르기",
    type: "single_choice",
    options: ["없음", "있음"],
    required: false,
    sensitivity: "sensitive_health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: true,
  },
  {
    id: "medical_allergy_detail",
    section: "medical",
    order: 5,
    label: "알레르기 상세",
    helperText: "알레르기가 있는 경우에만 적어 주세요.",
    type: "short_text",
    required: false,
    sensitivity: "sensitive_health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
    conditional: { questionId: "medical_food_allergy", operator: "equals", value: "있음" },
  },

  // ── lifestyle ───────────────────────────────────────────
  {
    id: "life_occupation",
    section: "lifestyle",
    order: 1,
    label: "직업 또는 주요 생활 패턴",
    type: "single_choice",
    options: [
      "주로 앉아서 일하는 사무직",
      "신체 활동이 많은 직종",
      "2~3교대 근무",
      "재택근무·전업주부",
      "학생",
    ],
    allowOther: true,
    required: false,
    sensitivity: "personal",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "life_exercise",
    section: "lifestyle",
    order: 2,
    label: "규칙적으로 하는 운동",
    type: "single_choice",
    options: ["없음", "있음"],
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: true,
    scoreDomain: "운동량",
    riskFlag: false,
  },
  {
    id: "life_exercise_detail",
    section: "lifestyle",
    order: 3,
    label: "운동 상세",
    helperText: "운동을 하는 경우 종류·주당 횟수·1회 시간을 적어 주세요.",
    type: "short_text",
    required: false,
    sensitivity: "health",
    dashboard: false,
    pdf: false,
    scoreCandidate: false,
    riskFlag: false,
    conditional: { questionId: "life_exercise", operator: "equals", value: "있음" },
  },

  // ── family ──────────────────────────────────────────────
  {
    id: "family_history",
    section: "family",
    order: 1,
    label: "가족 중 비만이거나 대사 관련 질환을 앓고 있는 분이 있으신가요?",
    type: "single_choice",
    options: ["없음", "있음"],
    required: false,
    sensitivity: "sensitive_health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
  },
  {
    id: "family_history_detail",
    section: "family",
    order: 2,
    label: "가족력 상세",
    helperText: "있는 경우 관계와 질환을 적어 주세요.",
    type: "short_text",
    required: false,
    sensitivity: "sensitive_health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
    conditional: { questionId: "family_history", operator: "equals", value: "있음" },
  },

  // ── final ───────────────────────────────────────────────
  {
    id: "final_message",
    section: "final",
    order: 1,
    label: "오늘 처음 상담에서 꼭 이야기 나누고 싶은 것이 있다면 자유롭게 적어 주세요.",
    helperText: "걱정, 궁금증, 기대, 두려움 모두 환영합니다.",
    type: "long_text",
    required: false,
    sensitivity: "health",
    dashboard: true,
    pdf: true,
    scoreCandidate: false,
    riskFlag: false,
  },
];

/** Fast lookup by question id. */
export const QUESTION_BY_ID: Record<string, SurveyQuestion> = Object.fromEntries(
  QUESTIONS.map((q) => [q.id, q]),
);
